name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    staging:
        name: Staging
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Terraform init
              uses: ./.github/actions/terraform-github-actions/init
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging
                  TF_ACTION_COMMENT: true
            - name: Terraform fmt
              uses: ./.github/actions/terraform-github-actions/fmt
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging
                  TF_ACTION_COMMENT: true
            - name: Terraform validate
              uses: ./.github/actions/terraform-github-actions/validate
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging
                  TF_ACTION_COMMENT: true
