name: CI

on:
    pull-request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    staging:
        name: Staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: ./bin/build staging 1SOF2sf218IFdLZhnqBlKB true
            - shell: bash
    production:
        name: Production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: ./bin/build staging 4oTgZx12jEy9ycSsrGmUW5 false
            - shell: bash
