name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    staging_terraform_fmt:
        name: Staging - terraform fmt
        runs-on: ubuntu-latest
        steps:
            - name: Terraform fmt
              uses: hashicorp/terraform-github-actions/fmt@v0.3.7
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: .tf/staging
    staging_terraform_init:
        name: Staging - terraform init
        needs: staging_terraform_fmt
        runs-on: ubuntu-latest
        steps:
            - name: Terraform init
              uses: hashicorp/terraform-github-actions/init@v0.3.7
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging
    staging_terraform_validate:
        name: Staging - terraform validate
        needs: staging_terraform_init
        runs-on: ubuntu-latest
        steps:
            - name: Terraform validate
              uses: hashicorp/terraform-github-actions/validate@v0.3.7
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging

