name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    staging:
        name: Staging
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Terraform init
              uses: ./.github/actions/terraform-github-actions/init
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging
            - name: Print Terraform version
              run: terraform version
            - name: Terraform fmt
              uses: ./.github/actions/terraform-github-actions/fmt
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging
            - name: Terraform validate
              uses: ./.github/actions/terraform-github-actions/validate
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging
            - name: Terraform import
              run: terraform import -input=false -config=tf/staging -no-color fastly_service_v1.api-service-staging-1SOF2sf218IFdLZhnqBlKB 1SOF2sf218IFdLZhnqBlKB
            - name: Print jq version
              run: jq --version
            - name: Add activate attribute to Terraform state
              run: jq '.resources[].instances[].attributes.activate = env.ACTIVATE' terraform.tfstate > temp && mv temp terraform.tfstate
            - name: Terraform plan
              uses: ./.github/actions/terraform-github-actions/plan
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TF_ACTION_WORKING_DIR: tf/staging
