name: CD - Production
on:
    push:
        branches:
            - master
jobs:
    production:
        name: Production
        runs-on: ubuntu-latest
        env:
            TF_ACTION_COMMENT: false
            TF_VAR_FASTLY_PRODUCTION_API_KEY: ${{ secrets.TF_VAR_FASTLY_PRODUCTION_API_KEY }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Terraform init
              uses: hashicorp/terraform-github-actions/init@v0.4.6
              with:
                  args: tf/production
            - name: Terraform version
              run: terraform --version
            - name: Terraform import
              run: terraform import -input=false -config=tf/production -no-color fastly_service_v1.api-service-production-0p7ElaomsexoNHwdMbYJac 0p7ElaomsexoNHwdMbYJac
            - name: Update activate attribute in Terraform state file
              run: jq '.resources[].instances[].attributes.activate = false' terraform.tfstate > temp && mv temp terraform.tfstate
            - name: Terraform plan
              id: plan
              uses: hashicorp/terraform-github-actions/plan@v0.4.6
              with:
                  args: -out=production.plan tf/production
            - name: Terraform apply
              uses: hashicorp/terraform-github-actions/apply@v0.4.6
              with:
                  args: production.plan
