name: CD - Staging
on:
    push:
        branches:
            - master
jobs:
    staging:
        name: Staging
        runs-on: ubuntu-latest
        env:
            TF_ACTION_COMMENT: false
            TF_VAR_FASTLY_STAGING_API_KEY: ${{ secrets.TF_VAR_FASTLY_STAGING_API_KEY }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Terraform init
              uses: hashicorp/terraform-github-actions/init@v0.4.6
              with:
                  args: tf/staging
            - name: Terraform version
              run: terraform --version
            - name: Terraform import
              run: terraform import -input=false -config=tf/staging -no-color fastly_service_v1.api-service-staging-1SOF2sf218IFdLZhnqBlKB 1SOF2sf218IFdLZhnqBlKB
            - name: Update activate attribute in Terraform state file
              run: jq '.resources[].instances[].attributes.activate = true' terraform.tfstate > temp && mv temp terraform.tfstate
            - name: Terraform plan
              id: plan
              uses: hashicorp/terraform-github-actions/plan@v0.4.6
              with:
                  args: ['tf/staging', '-out=staging.plan']
            - name: Terraform apply
              uses: hashicorp/terraform-github-actions/apply@v0.4.6
              with:
                  args: staging.plan
            - name: Fastly Terraform metadata
              id: metadata
              uses: philippschulte/fastly-terraform-metadata-action@master
              with:
                  tf_action_changes_present: ${{ steps.plan.outputs.changes-present }}
            - name: Print Fastly Service metadata
              if: ${{ steps.plan.outputs.changes-present }} == 'true'
              run: |
                  echo "${{ steps.metadata.outputs.fastly_service_config_url }}"
                  echo "${{ steps.metadata.outputs.fastly_service_version_info }}"
                  echo "${{ steps.metadata.outputs.fastly_service_id }}"
                  echo "${{ steps.metadata.outputs.fastly_active_version }}"
