name: CD - Staging
on:
  push:
    branches:
      - master
jobs:
  staging:
    name: 'Terraform: plan, apply'
    runs-on: ubuntu-latest
    env:
      TF_VAR_FASTLY_STAGING_API_KEY: ${{ secrets.TF_VAR_FASTLY_STAGING_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@81c27694e1545b2b39333169f11d5b4301897be2
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: init
          tf_actions_comment: false
          args: tf/staging
      - name: Terraform Import
        run: terraform import -input=false -config=tf/staging -no-color fastly_service_v1.api-service-staging-1SOF2sf218IFdLZhnqBlKB 1SOF2sf218IFdLZhnqBlKB
      - name: Update Terraform State
        run: jq '.resources[].instances[].attributes.activate = true' terraform.tfstate > temp && mv temp terraform.tfstate
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@81c27694e1545b2b39333169f11d5b4301897be2
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: plan
          tf_actions_comment: false
          args: -out=staging.plan tf/staging
      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@81c27694e1545b2b39333169f11d5b4301897be2
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: apply
          tf_actions_comment: false
          args: staging.plan
