name: CI - Production
on:
  pull_request:
    branches:
      - master
jobs:
  production:
    name: 'Terraform: format, validate, plan'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_FASTLY_PRODUCTION_API_KEY: ${{ secrets.TF_VAR_FASTLY_PRODUCTION_API_KEY }}
      TF_VAR_GCS_LOGGING_NAME: ${{ secrets.TF_VAR_GCS_LOGGING_NAME }}
      TF_VAR_GCS_LOGGING_SECRET_KEY: ${{ secrets.TF_VAR_GCS_LOGGING_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@81c27694e1545b2b39333169f11d5b4301897be2
        with:
          tf_actions_version: 0.12.19
          tf_actions_subcommand: init
          args: tf/production
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@81c27694e1545b2b39333169f11d5b4301897be2
        with:
          tf_actions_version: 0.12.19
          tf_actions_subcommand: fmt
          args: tf/production
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@81c27694e1545b2b39333169f11d5b4301897be2
        with:
          tf_actions_version: 0.12.19
          tf_actions_subcommand: validate
          args: tf/production
      - name: Terraform Import
        run: terraform import -input=false -config=tf/production -no-color fastly_service_v1.api-service-production-0p7ElaomsexoNHwdMbYJac 0p7ElaomsexoNHwdMbYJac
      - name: Update Terraform State
        run: jq '.resources[].instances[].attributes.activate = false' terraform.tfstate > temp && mv temp terraform.tfstate
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@81c27694e1545b2b39333169f11d5b4301897be2
        with:
          tf_actions_version: 0.12.19
          tf_actions_subcommand: plan
          args: tf/production
