name: CI - Staging
on:
  pull_request:
    branches:
      - master
jobs:
  staging:
    name: init, fmt, validate, import, plan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VERSION: latest
      TF_DIRECTORY: tf/staging
      TF_DEPLOYMENT_ID: fastly_service_v1
      TF_RESOURCE_ID: api-service-staging-1SOF2sf218IFdLZhnqBlKB
      TF_SERVICE_ID: 1SOF2sf218IFdLZhnqBlKB
      TF_VAR_FASTLY_STAGING_API_KEY: ${{ secrets.TF_VAR_FASTLY_STAGING_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@1acd6aa693246e33c9d49f861878fc5813736d47
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: init
          args: ${{ env.TF_DIRECTORY }}
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@1acd6aa693246e33c9d49f861878fc5813736d47
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: fmt
          args: ${{ env.TF_DIRECTORY }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@1acd6aa693246e33c9d49f861878fc5813736d47
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: validate
          args: ${{ env.TF_DIRECTORY }}
      - name: Terraform Import
        uses: hashicorp/terraform-github-actions@1acd6aa693246e33c9d49f861878fc5813736d47
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: import
          args: -config=${{ env.TF_DIRECTORY }} -no-color ${{ env.TF_DEPLOYMENT_ID }}.${{ env.TF_RESOURCE_ID }} ${{ env.TF_SERVICE_ID }}
      - name: Update Terraform State
        run: jq '.resources[].instances[].attributes.activate = true' terraform.tfstate > temp && mv temp terraform.tfstate
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@1acd6aa693246e33c9d49f861878fc5813736d47
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: plan
          args: ${{ env.TF_DIRECTORY }}
