name: CD

on:
    push:
        branches:
            - master

jobs:
    staging:
        name: Staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Terraform staging build tasks
              env:
                  TF_VAR_FASTLY_STAGING_API_KEY: ${{ secrets.TF_VAR_FASTLY_STAGING_API_KEY }}
              run: ./bin/deploy staging 1SOF2sf218IFdLZhnqBlKB true
              shell: bash
    production:
        name: Production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Terraform production build tasks
              env:
                  TF_VAR_FASTLY_PRODUCTION_API_KEY: ${{ secrets.TF_VAR_FASTLY_PRODUCTION_API_KEY }}
              run: ./bin/deploy production 0p7ElaomsexoNHwdMbYJac false
              shell: bash
